### ISSUE TITLE
你好，请问可以提供smp-ecdt2019的数据吗？

### ISSUE THREAD

**Issue by dy-ux** [BillKiller/GAIR-SLU#1]

**Comment by BillKiller** [comment]
请提供一下邮件地址

**Comment by dy-ux** [comment]
***@***.***
麻烦您了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月16日 12:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BillKiller/GAIR-SLU] 你好，请问可以提供smp-ecdt2019的数据吗？ (Issue #1) |

请提供一下邮件地址

**Comment by BillKiller** [comment]
我们提交了smp数据集，你可以直接下载，正如论文所说smp比赛只提供了训练集，这是我们根据训练集切分构造数据集。
